const PRODUCTS = [
  {
    "id": 0,
    "brand": "Sipcam",
    "code": "0007414",
    "name": "Metrimex",
    "variant": "500SC",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Biológicos",
    "bulaLink": "https://www.adapar.pr.gov.br/sites/adapar/arquivos_restritos/files/documento/2021-03/metrimex500sc.pdf",
    "notes": "Princípio ativo: Ametrina (500g/L)",
    "slug": "metrimex-500sc",
    "image": "assets/img/products/metrimex-5-lt-340x340.jpg"
  },
  {
    "id": 1,
    "brand": "Sipcam",
    "code": "0007445",
    "name": "Soleado",
    "variant": "50WG",
    "pkgType": "PC",
    "content": "250g",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "https://www.adapar.pr.gov.br/sites/adapar/arquivos_restritos/files/documento/2024-10/soleado_50_wg.pdf",
    "notes": "Princípio Ativo: Boscalida (500g/kg)",
    "slug": "soleado-50wg",
    "image": ""
  },
  {
    "id": 2,
    "brand": "Sipcam",
    "code": "0007417",
    "name": "Cuprozeb",
    "variant": "WG",
    "pkgType": "SC",
    "content": "2kg",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "https://www.adapar.pr.gov.br/sites/adapar/arquivos_restritos/files/documento/2025-03/cuprozeb.pdf",
    "notes": "Princípio Ativo: Mancozebe (440g/kg), Oxicloreto de cobre (300g/kg)",
    "slug": "cuprozeb-wg",
    "image": ""
  },
  {
    "id": 3,
    "brand": "Sipcam",
    "code": "0007415",
    "name": "Metiltiofan",
    "variant": "700WP",
    "pkgType": "SC",
    "content": "1kg",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "https://www.adapar.pr.gov.br/sites/adapar/arquivos_restritos/files/documento/2022-02/metiltiofan_0.pdf",
    "notes": "Princípio Ativo: Tiofanato-Metílico (700g/kg)",
    "slug": "metiltiofan-700wp",
    "image": ""
  },
  {
    "id": 4,
    "brand": "Sipcam",
    "code": "0007416",
    "name": "Elios",
    "variant": "800WG",
    "pkgType": "SC",
    "content": "2kg",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "https://assets.revistacultivar.com.br/c24984fe-9a22-46c3-9c50-928ca5caccf0_elios_800_wg_bula.pdf",
    "notes": "Princípio Ativo: Boscalida (800g/kg)",
    "slug": "elios-800wg",
    "image": ""
  },
  {
    "id": 5,
    "brand": "Gowan",
    "code": "0007206",
    "name": "Kentan",
    "variant": "40WG",
    "pkgType": "SC",
    "content": "5kg",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "https://gowan.com.br/documentos/BULA-KENTAN-40-WG.pdf",
    "notes": "Princípio Ativo: Hidroxido de cobre (656g/kg)",
    "slug": "kentan-40wg",
    "image": ""
  },
  {
    "id": 6,
    "brand": "Gowan",
    "code": "0000086",
    "name": "Volcane",
    "variant": "SL",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "https://www.gowan.com.br/documentos/BULA-VOLCANE.pdf",
    "notes": "Princípio Ativo: Sodium hydrogen methylarsonate (MSMA) (790g/L)",
    "slug": "volcane-sl",
    "image": ""
  },
  {
    "id": 7,
    "brand": "Gowan",
    "code": "0007457",
    "name": "Perimeter",
    "variant": "SL",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "https://gowan.com.br/documentos/BULA_PERIMETER.pdf",
    "notes": "Princípio Ativo: Extrato de Swinglea glutinosa (868,40g/L)",
    "slug": "perimeter-sl",
    "image": ""
  },
  {
    "id": 8,
    "brand": "Gowan",
    "code": "0004160",
    "name": "Monceren",
    "variant": "250SC",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "https://www.gowan.com.br/documentos/BULA-MONCEREN-250-SC.pdf",
    "notes": "Princípio Ativo: Pencicurom (250g/L)",
    "slug": "monceren-250sc",
    "image": ""
  },
  {
    "id": 9,
    "brand": "Tide",
    "code": "0006168",
    "name": "GLIFOSATO POCCO PRENTISS - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "glifosato-pocco-prentiss-1-lt",
    "image": ""
  },
  {
    "id": 10,
    "brand": "Tide",
    "code": "0006169",
    "name": "GLIFOSATO POCCO PRENTISS - 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "glifosato-pocco-prentiss-5-lt",
    "image": ""
  },
  {
    "id": 11,
    "brand": "Tide",
    "code": "0006170",
    "name": "GLIFOSATO POCCO PRENTISS  - 20LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "glifosato-pocco-prentiss-20lt",
    "image": ""
  },
  {
    "id": 12,
    "brand": "Tide",
    "code": "0006496",
    "name": "CAMP D-1 LT (2,4-D e Picloram)",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "camp-d-1-lt-2-4-d-e-picloram",
    "image": ""
  },
  {
    "id": 13,
    "brand": "Tide",
    "code": "0006248",
    "name": "CAMP D-5 LT (2,4-D e Picloram)",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "camp-d-5-lt-2-4-d-e-picloram",
    "image": ""
  },
  {
    "id": 14,
    "brand": "Tide",
    "code": "0006696",
    "name": "CAMP D-20 LT (2,4-D e Picloram)",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "camp-d-20-lt-2-4-d-e-picloram",
    "image": ""
  },
  {
    "id": 15,
    "brand": "Tide",
    "code": "0006322",
    "name": "CLORIMUROM PRENTISS - 300GR",
    "variant": "",
    "pkgType": "PCT",
    "content": "300GR",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "clorimurom-prentiss-300gr",
    "image": ""
  },
  {
    "id": 16,
    "brand": "Tide",
    "code": "0007203",
    "name": "METSULFUROM ULTRA 600 WG - 200 GR (Substitui o Zartan)",
    "variant": "",
    "pkgType": "PCT",
    "content": "200GR",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "metsulfurom-ultra-600-wg-200-gr-substitui-o-zartan",
    "image": ""
  },
  {
    "id": 17,
    "brand": "Tide",
    "code": "0006565",
    "name": "PREN-D 1 LT (Substitui o DMA, Aminol, U46)",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "pren-d-1-lt-substitui-o-dma-aminol-u46",
    "image": ""
  },
  {
    "id": 18,
    "brand": "Tide",
    "code": "0007269",
    "name": "PREN-D 5 LT (Substitui o DMA, Aminol, U46)",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "pren-d-5-lt-substitui-o-dma-aminol-u46",
    "image": ""
  },
  {
    "id": 19,
    "brand": "Tide",
    "code": "0006166",
    "name": "STATION 1 LT (Picloram)",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "station-1-lt-picloram",
    "image": ""
  },
  {
    "id": 20,
    "brand": "Tide",
    "code": "0007334",
    "name": "STATION 5 LT (Picloram)",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "station-5-lt-picloram",
    "image": ""
  },
  {
    "id": 21,
    "brand": "Tide",
    "code": "0007335",
    "name": "STATION 20 LT (Picloram)",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "station-20-lt-picloram",
    "image": ""
  },
  {
    "id": 22,
    "brand": "Tide",
    "code": "0007336",
    "name": "TRICLOPIR TID 480 EC 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "triclopir-tid-480-ec-5-lt",
    "image": ""
  },
  {
    "id": 23,
    "brand": "Tide",
    "code": "0007337",
    "name": "TRICLOPIR TID 480 EC 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "triclopir-tid-480-ec-20-lt",
    "image": ""
  },
  {
    "id": 24,
    "brand": "Tide",
    "code": "0007424",
    "name": "WIKING 600 WG - 200 GR (Substitui o Zartan)",
    "variant": "",
    "pkgType": "PCT",
    "content": "200G",
    "category": "Defensivos",
    "subcategory": "Geral",
    "bulaLink": "",
    "notes": "",
    "slug": "wiking-600-wg-200-gr-substitui-o-zartan",
    "image": ""
  },
  {
    "id": 25,
    "brand": "Neo",
    "code": "0007487",
    "name": "NEO AMINO 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-amino-1-lt",
    "image": "assets/img/products/neo-amino-1l.png"
  },
  {
    "id": 26,
    "brand": "Neo",
    "code": "0007488",
    "name": "NEO AMINO 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-amino-5-lt",
    "image": "assets/img/products/neo-amino-1l.png"
  },
  {
    "id": 27,
    "brand": "Neo",
    "code": "0007489",
    "name": "NEO AMINO 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-amino-20-lt",
    "image": "assets/img/products/neo-amino-1l.png"
  },
  {
    "id": 28,
    "brand": "Neo",
    "code": "0007236",
    "name": "NEO BORO 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5LT",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-boro-5-lt",
    "image": "assets/img/products/neo-boro-5l-v2.png"
  },
  {
    "id": 29,
    "brand": "Neo",
    "code": "0007237",
    "name": "NEO BORO 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-boro-20-lt",
    "image": "assets/img/products/neo-boro-5l-v2.png"
  },
  {
    "id": 30,
    "brand": "Neo",
    "code": "0007246",
    "name": "NEO CAB 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-cab-5-lt",
    "image": "assets/img/products/neo-cab-5l-v2.png"
  },
  {
    "id": 31,
    "brand": "Neo",
    "code": "0007245",
    "name": "NEO CAB 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-cab-20-lt",
    "image": "assets/img/products/neo-cab-5l-v2.png"
  },
  {
    "id": 32,
    "brand": "Neo",
    "code": "0007241",
    "name": "NEO HUMIC 5LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-humic-5lt",
    "image": "assets/img/products/neo-humic-5l-v2.png"
  },
  {
    "id": 33,
    "brand": "Neo",
    "code": "0007229",
    "name": "NEO HUMIC 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-humic-20-lt",
    "image": "assets/img/products/neo-humic-5l-v2.png"
  },
  {
    "id": 34,
    "brand": "Neo",
    "code": "0007238",
    "name": "NEO GOLD 1LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-gold-1lt",
    "image": "assets/img/products/neo-gold-1l-v2.png"
  },
  {
    "id": 35,
    "brand": "Neo",
    "code": "0007239",
    "name": "NEO GOLD 5LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-gold-5lt",
    "image": "assets/img/products/neo-gold-1l-v2.png"
  },
  {
    "id": 36,
    "brand": "Neo",
    "code": "0007240",
    "name": "NEO GOLD 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-gold-20-lt",
    "image": "assets/img/products/neo-gold-1l-v2.png"
  },
  {
    "id": 37,
    "brand": "Neo",
    "code": "0007426",
    "name": "NEO MAG 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-mag-1-lt",
    "image": "assets/img/products/neo-mag-5l-v2.png"
  },
  {
    "id": 38,
    "brand": "Neo",
    "code": "0007427",
    "name": "NEO MAG 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-mag-5-lt",
    "image": "assets/img/products/neo-mag-5l-v2.png"
  },
  {
    "id": 39,
    "brand": "Neo",
    "code": "0007428",
    "name": "NEO MAG 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-mag-20-lt",
    "image": "assets/img/products/neo-mag-5l-v2.png"
  },
  {
    "id": 40,
    "brand": "Neo",
    "code": "0007234",
    "name": "NEO MIX 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-mix-5-lt",
    "image": "assets/img/products/neo-mix-1000l-v2.png"
  },
  {
    "id": 41,
    "brand": "Neo",
    "code": "0007235",
    "name": "NEO MIX 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-mix-20-lt",
    "image": "assets/img/products/neo-mix-1000l-v2.png"
  },
  {
    "id": 42,
    "brand": "Neo",
    "code": "0007242",
    "name": "NEO MIX 1000 LT",
    "variant": "",
    "pkgType": "IBD",
    "content": "1000L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-mix-1000-lt",
    "image": "assets/img/products/neo-mix-1000l-v2.png"
  },
  {
    "id": 43,
    "brand": "Neo",
    "code": "0007232",
    "name": "NEO N 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-n-5-lt",
    "image": "assets/img/products/neo-amino-5l.png"
  },
  {
    "id": 44,
    "brand": "Neo",
    "code": "0007233",
    "name": "NEO N 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-n-20-lt",
    "image": "assets/img/products/neo-amino-20l.png"
  },
  {
    "id": 45,
    "brand": "Neo",
    "code": "0007230",
    "name": "NEO SPRAY 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1LT",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-spray-1-lt",
    "image": "assets/img/products/neo-spray-5l-v2.png"
  },
  {
    "id": 46,
    "brand": "Neo",
    "code": "0007231",
    "name": "NEO SPRAY 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-spray-5-lt",
    "image": "assets/img/products/neo-spray-5l-v2.png"
  },
  {
    "id": 47,
    "brand": "Neo",
    "code": "0007425",
    "name": "NEO ZINC 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-zinc-1-lt",
    "image": "assets/img/products/neo-zinc-5l-v2.png"
  },
  {
    "id": 48,
    "brand": "Neo",
    "code": "0007243",
    "name": "NEO ZINC 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-zinc-5-lt",
    "image": "assets/img/products/neo-zinc-5l-v2.png"
  },
  {
    "id": 49,
    "brand": "Neo",
    "code": "0007244",
    "name": "NEO ZINC 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-zinc-20-lt",
    "image": "assets/img/products/neo-zinc-5l-v2.png"
  },
  {
    "id": 50,
    "brand": "ICL",
    "code": "0007162",
    "name": "BIOZ KELLUS COPPER 3KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "3KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "bioz-kellus-copper-3kg",
    "image": ""
  },
  {
    "id": 51,
    "brand": "ICL",
    "code": "0006369",
    "name": "CONCORDE RN 5 LTS",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "concorde-rn-5-lts",
    "image": ""
  },
  {
    "id": 52,
    "brand": "ICL",
    "code": "0006493",
    "name": "CONCORDE RN 20 LTS",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "concorde-rn-20-lts",
    "image": ""
  },
  {
    "id": 53,
    "brand": "ICL",
    "code": "0006521",
    "name": "ENERGY SC 10 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "10KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "energy-sc-10-kg",
    "image": ""
  },
  {
    "id": 54,
    "brand": "ICL",
    "code": "0007163",
    "name": "HELPER AIR ADJT 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "helper-air-adjt-1-lt",
    "image": ""
  },
  {
    "id": 55,
    "brand": "ICL",
    "code": "0006748",
    "name": "HELPER DESSEK 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "helper-dessek-1-lt",
    "image": ""
  },
  {
    "id": 56,
    "brand": "ICL",
    "code": "0006459",
    "name": "HELPER NEUTRUM ADJ 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "helper-neutrum-adj-1-lt",
    "image": ""
  },
  {
    "id": 57,
    "brand": "ICL",
    "code": "0007262",
    "name": "HELPER NEUTRUM ADJ 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "helper-neutrum-adj-5-lt",
    "image": ""
  },
  {
    "id": 58,
    "brand": "ICL",
    "code": "0006338",
    "name": "HELPER PERENES 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "helper-perenes-1-lt",
    "image": ""
  },
  {
    "id": 59,
    "brand": "ICL",
    "code": "0006337",
    "name": "KEEP GREEN 5 LTS",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "keep-green-5-lts",
    "image": ""
  },
  {
    "id": 60,
    "brand": "ICL",
    "code": "0006321",
    "name": "KEEP GREEN 25 LTS",
    "variant": "",
    "pkgType": "BD",
    "content": "25L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "keep-green-25-lts",
    "image": ""
  },
  {
    "id": 61,
    "brand": "ICL",
    "code": "0006367",
    "name": "KELLUS COPPER 3 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "3KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "kellus-copper-3-kg",
    "image": ""
  },
  {
    "id": 62,
    "brand": "ICL",
    "code": "0006522",
    "name": "KELLUS IMUNE 5KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "5KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "kellus-imune-5kg",
    "image": ""
  },
  {
    "id": 63,
    "brand": "ICL",
    "code": "0006461",
    "name": "KELLUS MANGANESE 3KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "3KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "kellus-manganese-3kg",
    "image": ""
  },
  {
    "id": 64,
    "brand": "ICL",
    "code": "0006370",
    "name": "KELLUS ZINCO RN 3 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "3KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "kellus-zinco-rn-3-kg",
    "image": ""
  },
  {
    "id": 65,
    "brand": "ICL",
    "code": "0007164",
    "name": "NUTRIDUO 10 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "10KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "nutriduo-10-kg",
    "image": ""
  },
  {
    "id": 66,
    "brand": "ICL",
    "code": "0006365",
    "name": "PROFOL EXCLUSIVE 5 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "5KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "profol-exclusive-5-kg",
    "image": ""
  },
  {
    "id": 67,
    "brand": "ICL",
    "code": "0006465",
    "name": "PROFOL PRODUTIVIDADE 12 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "12KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "profol-produtividade-12-kg",
    "image": ""
  },
  {
    "id": 68,
    "brand": "ICL",
    "code": "0006523",
    "name": "PROFOL SAIS 25 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "25KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "profol-sais-25-kg",
    "image": ""
  },
  {
    "id": 69,
    "brand": "ICL",
    "code": "0006466",
    "name": "TRANSLOC 10 KG (NUTRIDUO)",
    "variant": "",
    "pkgType": "PCT",
    "content": "10KG",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "transloc-10-kg-nutriduo",
    "image": ""
  },
  {
    "id": 70,
    "brand": "ICL",
    "code": "0006368",
    "name": "TRIPLUS PERENES 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "triplus-perenes-1-lt",
    "image": ""
  },
  {
    "id": 71,
    "brand": "AJINOMOTO",
    "code": "0006646",
    "name": "AMIORGAN - 25 KG",
    "variant": "",
    "pkgType": "SC",
    "content": "25KG",
    "category": "Fertilizantes",
    "subcategory": "Granulados",
    "bulaLink": "",
    "notes": "",
    "slug": "amiorgan-25-kg",
    "image": ""
  },
  {
    "id": 72,
    "brand": "AJINOMOTO",
    "code": "0005878",
    "name": "AJIFOL CÁLCIO - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-c-lcio-1-lt",
    "image": ""
  },
  {
    "id": 73,
    "brand": "AJINOMOTO",
    "code": "0006331",
    "name": "AJIFOL GOLD MAIS - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-gold-mais-1-lt",
    "image": ""
  },
  {
    "id": 74,
    "brand": "AJINOMOTO",
    "code": "0006532",
    "name": "AJIFOL KMG POTENCY - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-kmg-potency-1-lt",
    "image": ""
  },
  {
    "id": 75,
    "brand": "AJINOMOTO",
    "code": "0006332",
    "name": "AJIFOL PREMIUM MAIS - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-premium-mais-1-lt",
    "image": ""
  },
  {
    "id": 76,
    "brand": "AJINOMOTO",
    "code": "0006586",
    "name": "AJIFOL RHIZO-MO - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-rhizo-mo-1-lt",
    "image": ""
  },
  {
    "id": 77,
    "brand": "AJINOMOTO",
    "code": "0005879",
    "name": "AJIFOL SM BORO - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-sm-boro-1-lt",
    "image": ""
  },
  {
    "id": 78,
    "brand": "AJINOMOTO",
    "code": "0006067",
    "name": "AJIFOL SM BORO - 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-sm-boro-20-lt",
    "image": ""
  },
  {
    "id": 79,
    "brand": "AJINOMOTO",
    "code": "0005955",
    "name": "AJIFOL SM BORO - 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajifol-sm-boro-5-lt",
    "image": ""
  },
  {
    "id": 80,
    "brand": "AJINOMOTO",
    "code": "0006587",
    "name": "AJIPOWER - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "ajipower-1-lt",
    "image": ""
  },
  {
    "id": 81,
    "brand": "AJINOMOTO",
    "code": "0006333",
    "name": "AMINO ARGININE - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "amino-arginine-1-lt",
    "image": ""
  },
  {
    "id": 82,
    "brand": "AJINOMOTO",
    "code": "0006503",
    "name": "AMINO FORT (IMUNE) - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "amino-fort-imune-1-lt",
    "image": ""
  },
  {
    "id": 83,
    "brand": "AJINOMOTO",
    "code": "0005880",
    "name": "AMINO PLUS - 1 LT - SEM ESTOQUE",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "amino-plus-1-lt-sem-estoque",
    "image": ""
  },
  {
    "id": 84,
    "brand": "AJINOMOTO",
    "code": "0006335",
    "name": "AMINO PLUS - 5 LT - SEM ESTOQUE",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "amino-plus-5-lt-sem-estoque",
    "image": ""
  },
  {
    "id": 85,
    "brand": "AJINOMOTO",
    "code": "0006334",
    "name": "AMINO PROLINE - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Fertilizantes",
    "subcategory": "Foliares",
    "bulaLink": "",
    "notes": "",
    "slug": "amino-proline-1-lt",
    "image": ""
  },
  {
    "id": 86,
    "brand": "FMC",
    "code": "0002940",
    "name": "ALLY 60 XP - 40GR (Metsulfurom-Metílico)",
    "variant": "",
    "pkgType": "PCT",
    "content": "40GR",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "ally-60-xp-40gr-metsulfurom-met-lico",
    "image": ""
  },
  {
    "id": 87,
    "brand": "FMC",
    "code": "0000128",
    "name": "AURORA 400 EC - 1LT (Carfentrazona-Etílica)",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "aurora-400-ec-1lt-carfentrazona-et-lica",
    "image": ""
  },
  {
    "id": 88,
    "brand": "FMC",
    "code": "0000127",
    "name": "AURORA 400 EC - 250ML (Carfentrazona-Etílica)",
    "variant": "",
    "pkgType": "FRASCO",
    "content": "250ML",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "aurora-400-ec-250ml-carfentrazona-et-lica",
    "image": ""
  },
  {
    "id": 89,
    "brand": "FMC",
    "code": "0003764",
    "name": "ALTACOR 35 WG - 450 GR (Clorantraniliprole)",
    "variant": "",
    "pkgType": "ENVELOPE",
    "content": "450GR",
    "category": "Defensivos",
    "subcategory": "Inseticidas",
    "bulaLink": "",
    "notes": "",
    "slug": "altacor-35-wg-450-gr-clorantraniliprole",
    "image": ""
  },
  {
    "id": 90,
    "brand": "FMC",
    "code": "0006078",
    "name": "BORAL 500 SC - 1 LT (Sulfentrazona)",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "boral-500-sc-1-lt-sulfentrazona",
    "image": ""
  },
  {
    "id": 91,
    "brand": "FMC",
    "code": "0005212",
    "name": "PREMIO STAR - 1LT Clorantraniliprole (diamida antranílica) e Bifentrina (piretroide)",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Inseticidas",
    "bulaLink": "",
    "notes": "",
    "slug": "premio-star-1lt-clorantraniliprole-diamida-antran-lica-e-bifentrina-piretroide",
    "image": ""
  },
  {
    "id": 92,
    "brand": "Rainbow",
    "code": "0007461",
    "name": "GLINT FULL RAINBOW (Haloxifope-P-Metílico) - 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "glint-full-rainbow-haloxifope-p-met-lico-5-lt",
    "image": ""
  },
  {
    "id": 93,
    "brand": "Rainbow",
    "code": "0007463",
    "name": "ADICONSTAR RAINBOW (Azoxistrobina) - 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "adiconstar-rainbow-azoxistrobina-5-lt",
    "image": ""
  },
  {
    "id": 94,
    "brand": "Rainbow",
    "code": "0007464",
    "name": "FULLGUARD RAINBOW (Carfentrazona-Etílica) - 1 LT",
    "variant": "",
    "pkgType": "LT",
    "content": "1L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "fullguard-rainbow-carfentrazona-et-lica-1-lt",
    "image": ""
  },
  {
    "id": 95,
    "brand": "Rainbow",
    "code": "0007462",
    "name": "SOLDIER RAINBOW (Glifosato) - 5 KG",
    "variant": "",
    "pkgType": "PCT",
    "content": "5kg",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "soldier-rainbow-glifosato-5-kg",
    "image": ""
  },
  {
    "id": 96,
    "brand": "Rainbow",
    "code": "0007465",
    "name": "GLIFOSATO IPA 480 RAINBOW- 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "glifosato-ipa-480-rainbow-5-lt",
    "image": ""
  },
  {
    "id": 97,
    "brand": "Rainbow",
    "code": "0007466",
    "name": "GLIFOSATO IPA 480 RAINBOW - 20 LT",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Herbicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "glifosato-ipa-480-rainbow-20-lt",
    "image": ""
  },
  {
    "id": 98,
    "brand": "Rainbow",
    "code": "0007467",
    "name": "SKIP 125SC RAINBOW (Flutriafol) - 5 LT",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Inseticidas",
    "bulaLink": "",
    "notes": "",
    "slug": "skip-125sc-rainbow-flutriafol-5-lt",
    "image": ""
  },
  {
    "id": 99,
    "brand": "Ouro Fino",
    "code": "0007299",
    "name": "ACLAMADO BR 20 LT (Atrazina)",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Inseticidas",
    "bulaLink": "",
    "notes": "",
    "slug": "aclamado-br-20-lt-atrazina",
    "image": ""
  },
  {
    "id": 100,
    "brand": "Ouro Fino",
    "code": "0007294",
    "name": "PODERUS 20 LT (Azoxistrobina e Ciproconazol)",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Inseticidas",
    "bulaLink": "",
    "notes": "",
    "slug": "poderus-20-lt-azoxistrobina-e-ciproconazol",
    "image": ""
  },
  {
    "id": 101,
    "brand": "Ouro Fino",
    "code": "0007295",
    "name": "PODERUS 5 LT (Azoxistrobina e Ciproconazol)",
    "variant": "",
    "pkgType": "GL",
    "content": "5L",
    "category": "Defensivos",
    "subcategory": "Inseticidas",
    "bulaLink": "",
    "notes": "",
    "slug": "poderus-5-lt-azoxistrobina-e-ciproconazol",
    "image": ""
  },
  {
    "id": 102,
    "brand": "Ouro Fino",
    "code": "0007300",
    "name": "QUALLIS 20 LT (2,4-D (ácido 2,4-diclorofenoxiacético) e o picloram)",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "quallis-20-lt-2-4-d-cido-2-4-diclorofenoxiac-tico-e-o-picloram",
    "image": ""
  },
  {
    "id": 103,
    "brand": "Ouro Fino",
    "code": "0007296",
    "name": "TEBURAZ 20 LT (Estrobilurinas (azoxistrobina) e dos Triazóis (tebuconazol)",
    "variant": "",
    "pkgType": "BD",
    "content": "20L",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "teburaz-20-lt-estrobilurinas-azoxistrobina-e-dos-triaz-is-tebuconazol",
    "image": ""
  },
  {
    "id": 104,
    "brand": "Ouro Fino",
    "code": "0007298",
    "name": "VIVANTHA 1 KG (Tiametoxam)",
    "variant": "",
    "pkgType": "KG",
    "content": "1KG",
    "category": "Defensivos",
    "subcategory": "Fungicidas",
    "bulaLink": "",
    "notes": "",
    "slug": "vivantha-1-kg-tiametoxam",
    "image": ""
  },
  {
    "id": 105,
    "brand": "PANO-LONA-BAG",
    "code": "0007276",
    "name": "BIG BAG PADRAO COLHEITA 90 X 90 X 120",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "big-bag-padrao-colheita-90-x-90-x-120",
    "image": ""
  },
  {
    "id": 106,
    "brand": "PANO-LONA-BAG",
    "code": "0005505",
    "name": "PANO PARA CAFÉ 06 X 03",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-06-x-03",
    "image": ""
  },
  {
    "id": 107,
    "brand": "PANO-LONA-BAG",
    "code": "0004761",
    "name": "PANO PARA CAFÉ 08 X 03",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-08-x-03",
    "image": ""
  },
  {
    "id": 108,
    "brand": "PANO-LONA-BAG",
    "code": "0004762",
    "name": "PARA PARA CAFÉ 10 x 03",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "para-para-caf-10-x-03",
    "image": ""
  },
  {
    "id": 109,
    "brand": "PANO-LONA-BAG",
    "code": "0004763",
    "name": "PANO PARA CAFÉ 12X 03",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-12x-03",
    "image": ""
  },
  {
    "id": 110,
    "brand": "PANO-LONA-BAG",
    "code": "0005517",
    "name": "PANO PARA CAFÉ 15 X 03",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-15-x-03",
    "image": ""
  },
  {
    "id": 111,
    "brand": "PANO-LONA-BAG",
    "code": "0007574",
    "name": "PANO PARA CAFÉ 20 X 03",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-20-x-03",
    "image": ""
  },
  {
    "id": 112,
    "brand": "PANO-LONA-BAG",
    "code": "0003915",
    "name": "PARA PARA CAFÉ 08 X 04",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "para-para-caf-08-x-04",
    "image": ""
  },
  {
    "id": 113,
    "brand": "PANO-LONA-BAG",
    "code": "0003914",
    "name": "PANO PARA CAFÉ 10 X 04",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-10-x-04",
    "image": ""
  },
  {
    "id": 114,
    "brand": "PANO-LONA-BAG",
    "code": "0003916",
    "name": "PANO PARA CAFÉ 12 X 04",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-12-x-04",
    "image": ""
  },
  {
    "id": 115,
    "brand": "PANO-LONA-BAG",
    "code": "0005278",
    "name": "PANO PARA CAFÉ 15 X 04",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-15-x-04",
    "image": ""
  },
  {
    "id": 116,
    "brand": "PANO-LONA-BAG",
    "code": "0005552",
    "name": "PANO PARA CAFÉ 20 X 04",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-20-x-04",
    "image": ""
  },
  {
    "id": 117,
    "brand": "PANO-LONA-BAG",
    "code": "0005507",
    "name": "PANO PARA CAFÉ 10 X 04 - PRETO",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-10-x-04-preto",
    "image": ""
  },
  {
    "id": 118,
    "brand": "PANO-LONA-BAG",
    "code": "0005506",
    "name": "PANO PARA CAFÉ 12 X 04 - PRETO",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "pano-para-caf-12-x-04-preto",
    "image": ""
  },
  {
    "id": 119,
    "brand": "EQUIPAMENTO",
    "code": "0005993",
    "name": "LUVA C/ PIGMENTO PUNHO PRETO",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "luva-c-pigmento-punho-preto",
    "image": ""
  },
  {
    "id": 120,
    "brand": "EQUIPAMENTO",
    "code": "0000900",
    "name": "LUVA C/ PIGMENTO PUNHO AZUL - TAMANHO G",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "luva-c-pigmento-punho-azul-tamanho-g",
    "image": ""
  },
  {
    "id": 121,
    "brand": "EQUIPAMENTO",
    "code": "0005518",
    "name": "LUVA C/ PIGMENTO PUNHO VERMELHA - TAMANHO GG",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "luva-c-pigmento-punho-vermelha-tamanho-gg",
    "image": ""
  },
  {
    "id": 122,
    "brand": "EQUIPAMENTO",
    "code": "0007575",
    "name": "LUVA C/ PIGMENTO PUNHO LARANJA - TAMANHO GG",
    "variant": "",
    "pkgType": "PAR",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "luva-c-pigmento-punho-laranja-tamanho-gg",
    "image": ""
  },
  {
    "id": 123,
    "brand": "SACARIA",
    "code": "0005516",
    "name": "SACO 60 X 90 CONVENCIONAL",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "saco-60-x-90-convencional",
    "image": ""
  },
  {
    "id": 124,
    "brand": "SACARIA",
    "code": "0007302",
    "name": "SACO CONVENCIONAL 60X90CM BC LISTRA",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "saco-convencional-60x90cm-bc-listra",
    "image": ""
  },
  {
    "id": 125,
    "brand": "SACARIA",
    "code": "0005508",
    "name": "SACO CONVENCIONAL 60X100CM BC LISTRA",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "saco-convencional-60x100cm-bc-listra",
    "image": ""
  },
  {
    "id": 126,
    "brand": "SACARIA",
    "code": "0005509",
    "name": "SACO CONVENCIONAL 70X100CM BC LISTRA",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "saco-convencional-70x100cm-bc-listra",
    "image": ""
  },
  {
    "id": 127,
    "brand": "SACARIA",
    "code": "0005555",
    "name": "SACO CONVENCIONAL 70X110CM BC LISTRA",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "saco-convencional-70x110cm-bc-listra",
    "image": ""
  },
  {
    "id": 128,
    "brand": "SACARIA",
    "code": "0006176",
    "name": "SACO RAFIA LAMINADO MARRON 60 X 90 (USINA DO VALE)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "saco-rafia-laminado-marron-60-x-90-usina-do-vale",
    "image": ""
  },
  {
    "id": 129,
    "brand": "PANO-LONA-BAG",
    "code": "0002441  0007266",
    "name": "LONA PLAST. PRETA/BRANCA 8 X 50 - 40 KG (100 MICRAS)",
    "variant": "",
    "pkgType": "MT",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "lona-plast-preta-branca-8-x-50-40-kg-100-micras",
    "image": ""
  },
  {
    "id": 130,
    "brand": "PANO-LONA-BAG",
    "code": "0004724",
    "name": "LONA PLAST. PRETA/BRANCA 8 X 50 - 60 KG (150 MICRAS)",
    "variant": "",
    "pkgType": "MT",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "lona-plast-preta-branca-8-x-50-60-kg-150-micras",
    "image": ""
  },
  {
    "id": 131,
    "brand": "PANO-LONA-BAG",
    "code": "0006373",
    "name": "LONA PLAST. PRETA 4 X 110 - 40 KG (90 MICRAS)",
    "variant": "",
    "pkgType": "MT",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "lona-plast-preta-4-x-110-40-kg-90-micras",
    "image": ""
  },
  {
    "id": 132,
    "brand": "PANO-LONA-BAG",
    "code": "0005241",
    "name": "LONA PLAST. PRETA 6 X 50 - 30 KG (100 MICRAS)",
    "variant": "",
    "pkgType": "MT",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "lona-plast-preta-6-x-50-30-kg-100-micras",
    "image": ""
  },
  {
    "id": 133,
    "brand": "PANO-LONA-BAG",
    "code": "0003738",
    "name": "LONA PLAST. PRETA 8 X 50 - 40 KG (100 MICRAS)",
    "variant": "",
    "pkgType": "MT",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "lona-plast-preta-8-x-50-40-kg-100-micras",
    "image": ""
  },
  {
    "id": 134,
    "brand": "PANO-LONA-BAG",
    "code": "0003739",
    "name": "LONA PLAST. PRETA 8 X 50 - 60 KG (150 MICRAS)",
    "variant": "",
    "pkgType": "MT",
    "content": "",
    "category": "Produtos para colheita",
    "subcategory": "Diversos",
    "bulaLink": "",
    "notes": "",
    "slug": "lona-plast-preta-8-x-50-60-kg-150-micras",
    "image": ""
  },
  {
    "id": 136,
    "brand": "Husqvarna",
    "code": "0007228",
    "name": "DERRIÇADOR HUSQVARNA KD24 (DUPLO)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Derricadores",
    "bulaLink": "",
    "notes": "",
    "slug": "derri-ador-husqvarna-kd24-duplo",
    "image": ""
  },
  {
    "id": 137,
    "brand": "Husqvarna",
    "code": "0005181",
    "name": "MOTOCULTIVADOR HUSQVARNA - TF 338 (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Agricola",
    "bulaLink": "",
    "notes": "",
    "slug": "motocultivador-husqvarna-tf-338-imp",
    "image": ""
  },
  {
    "id": 138,
    "brand": "Husqvarna",
    "code": "0007583",
    "name": "MOTOCULTIVADOR HUSQVARNA - TF 440",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Agricola",
    "bulaLink": "",
    "notes": "",
    "slug": "motocultivador-husqvarna-tf-440",
    "image": ""
  },
  {
    "id": 139,
    "brand": "Husqvarna",
    "code": "0005201",
    "name": "MOTOSSERRA HUSQ. MOD. 120 14 PR 3/8 (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Motosserras",
    "bulaLink": "",
    "notes": "",
    "slug": "motosserra-husq-mod-120-14-pr-3-8-imp",
    "image": ""
  },
  {
    "id": 140,
    "brand": "Husqvarna",
    "code": "0000172",
    "name": "MOTOSSERRA HUSQ. MOD. 272 20 PD 3/8 (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Motosserras",
    "bulaLink": "",
    "notes": "",
    "slug": "motosserra-husq-mod-272-20-pd-3-8-imp",
    "image": ""
  },
  {
    "id": 141,
    "brand": "Husqvarna",
    "code": "0006474",
    "name": "MOTOSSERRA HUSQ. MOD. 281 20 PD 3/8",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Motosserras",
    "bulaLink": "",
    "notes": "",
    "slug": "motosserra-husq-mod-281-20-pd-3-8",
    "image": ""
  },
  {
    "id": 142,
    "brand": "Husqvarna",
    "code": "0000180",
    "name": "MOTOSSERRA HUSQ. MOD. 288 24 PD 3/8 (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Motosserras",
    "bulaLink": "",
    "notes": "",
    "slug": "motosserra-husq-mod-288-24-pd-3-8-imp",
    "image": ""
  },
  {
    "id": 143,
    "brand": "Husqvarna",
    "code": "0001890",
    "name": "MOTOSSERRA HUSQ. MOD. 61 18 PD 3/8 (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Motosserras",
    "bulaLink": "",
    "notes": "",
    "slug": "motosserra-husq-mod-61-18-pd-3-8-imp",
    "image": ""
  },
  {
    "id": 144,
    "brand": "Husqvarna",
    "code": "0006484",
    "name": "PERFURADOR DE SOLO 541 EA",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Motosserras",
    "bulaLink": "",
    "notes": "",
    "slug": "perfurador-de-solo-541-ea",
    "image": ""
  },
  {
    "id": 145,
    "brand": "Husqvarna",
    "code": "0007278",
    "name": "ROÇADEIRA HUSQ. MOD. 143RS",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Roçadeiras",
    "bulaLink": "",
    "notes": "",
    "slug": "ro-adeira-husq-mod-143rs",
    "image": ""
  },
  {
    "id": 146,
    "brand": "Husqvarna",
    "code": "0005867",
    "name": "ROÇADEIRA HUSQ. MOD. 226K BR",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Roçadeiras",
    "bulaLink": "",
    "notes": "",
    "slug": "ro-adeira-husq-mod-226k-br",
    "image": ""
  },
  {
    "id": 147,
    "brand": "Husqvarna",
    "code": "0006139",
    "name": "ROÇADEIRA HUSQ. MOD. 226RJ BR",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Roçadeiras",
    "bulaLink": "",
    "notes": "",
    "slug": "ro-adeira-husq-mod-226rj-br",
    "image": ""
  },
  {
    "id": 148,
    "brand": "Husqvarna",
    "code": "0007476",
    "name": "ROÇADEIRA HUSQ. MOD. 541RB",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Roçadeiras",
    "bulaLink": "",
    "notes": "",
    "slug": "ro-adeira-husq-mod-541rb",
    "image": ""
  },
  {
    "id": 149,
    "brand": "Husqvarna",
    "code": "0003851",
    "name": "SOPRADOR HUSQ. MOD: 570BTS (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Sopradores",
    "bulaLink": "",
    "notes": "",
    "slug": "soprador-husq-mod-570bts-imp",
    "image": ""
  },
  {
    "id": 150,
    "brand": "Husqvarna",
    "code": "0003220",
    "name": "SOPRADOR HUSQ. MOD:125 B (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Sopradores",
    "bulaLink": "",
    "notes": "",
    "slug": "soprador-husq-mod-125-b-imp",
    "image": ""
  },
  {
    "id": 151,
    "brand": "Husqvarna",
    "code": "0000281",
    "name": "SOPRADOR HUSQ. MOD:125 BVX (IMP.)",
    "variant": "",
    "pkgType": "UND",
    "content": "",
    "category": "Jardinagem/Uso Agrícola",
    "subcategory": "Sopradores",
    "bulaLink": "",
    "notes": "",
    "slug": "soprador-husq-mod-125-bvx-imp",
    "image": ""
  },
  {
    "id": 152,
    "brand": "Phox Fertilizantes",
    "code": "0007433",
    "name": "ACELERAFOS - SC 25 KG",
    "variant": "25kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "acelerafos-sc-25-kg-25kg",
    "image": ""
  },
  {
    "id": 153,
    "brand": "Neo",
    "code": "0006615",
    "name": "NEO 02-18-00 + 8% CA (F) - SC 50 KG",
    "variant": "50kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Organo mineral",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-02-18-00-8-ca-f-sc-50-kg-50kg",
    "image": ""
  },
  {
    "id": 154,
    "brand": "Neo",
    "code": "0006677",
    "name": "NEO 10-02-10 + 10%S + 0,3 B + 0,2 Zn (P) - SC 50 KG",
    "variant": "50kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Organo mineral",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-10-02-10-10-s-0-3-b-0-2-zn-p-sc-50-kg-50kg",
    "image": ""
  },
  {
    "id": 155,
    "brand": "Neo",
    "code": "0006612",
    "name": "NEO 14-02-10 (F) - SC 50 KG",
    "variant": "50kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Organo mineral",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-14-02-10-f-sc-50-kg-50kg",
    "image": ""
  },
  {
    "id": 156,
    "brand": "Neo",
    "code": "0006610",
    "name": "NEO 14-02-14 (F) - SC 50 KG",
    "variant": "50kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Organo mineral",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-14-02-14-f-sc-50-kg-50kg",
    "image": ""
  },
  {
    "id": 157,
    "brand": "Neo",
    "code": "0006576",
    "name": "NEO 14-02-08 (F) - SC 50 KG",
    "variant": "50kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Organo mineral",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-14-02-08-f-sc-50-kg-50kg",
    "image": ""
  },
  {
    "id": 158,
    "brand": "Neo",
    "code": "0006616",
    "name": "NEO 29-00-00 (F) SC 50 KG",
    "variant": "50kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Organo mineral",
    "bulaLink": "",
    "notes": "",
    "slug": "neo-29-00-00-f-sc-50-kg-50kg",
    "image": ""
  },
  {
    "id": 159,
    "brand": "Geox",
    "code": "0006655",
    "name": "Geox HD ( Hidrolizado pó ) 45% CaO + 20% MgO PRNT 134 Big Bag 500 kg",
    "variant": "500kg",
    "pkgType": "Bag",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "geox-hd-hidrolizado-p-45-cao-20-mgo-prnt-134-big-bag-500-kg-500kg",
    "image": ""
  },
  {
    "id": 160,
    "brand": "Geox",
    "code": "0005997",
    "name": "Geox HD ( Hidrolizado pó ) 45% CaO + 20% MgO PRNT 134 Ensacado 25 kg",
    "variant": "25kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "geox-hd-hidrolizado-p-45-cao-20-mgo-prnt-134-ensacado-25-kg-25kg",
    "image": ""
  },
  {
    "id": 161,
    "brand": "Geox",
    "code": "0006656",
    "name": "Geox DUO (44% CaO + 18% MgO ) produto de Dupla Liberação OXido + Carbonato. PRNT 120 Big Bag 500 kg",
    "variant": "500kg",
    "pkgType": "Bag",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "geox-duo-44-cao-18-mgo-produto-de-dupla-libera-o-oxido-carbonato-prnt-120-big-bag-500-kg-500kg",
    "image": ""
  },
  {
    "id": 162,
    "brand": "Geox",
    "code": "0006734",
    "name": "Geox Super S - (54% CaO + 18% MgO + 11% SO3 Fertilizante Misto) Produto Substituí Calcario e Gesso Big Bag 500 kg",
    "variant": "500kg",
    "pkgType": "Bag",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "geox-super-s-54-cao-18-mgo-11-so3-fertilizante-misto-produto-substitu-calcario-e-gesso-big-bag-500-kg-500kg",
    "image": ""
  },
  {
    "id": 163,
    "brand": "Geox",
    "code": "0006731",
    "name": "ACTIVE Pó - Ensacado 25 kg",
    "variant": "25kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "active-p-ensacado-25-kg-25kg",
    "image": ""
  },
  {
    "id": 164,
    "brand": "caltim",
    "code": "0006213",
    "name": "CALTIMAG - SC 40 KG",
    "variant": "40kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "caltimag-sc-40-kg-40kg",
    "image": ""
  },
  {
    "id": 165,
    "brand": "caltim",
    "code": "0006678",
    "name": "CALTIMAG + BORO - SC 40 KG",
    "variant": "40kg",
    "pkgType": "SC",
    "content": "",
    "category": "Fertilizantes",
    "subcategory": "Corretivos",
    "bulaLink": "",
    "notes": "",
    "slug": "caltimag-boro-sc-40-kg-40kg",
    "image": ""
  }
];
